### PR TITLE
Add scss lang support

### PR DESCRIPTION
**Pull request by dio-az**
``` vue
<style lang="scss">
  ...
</style>
```

### CODE REVIEW

**Comment by GregPeden** [comment]
I'm pretty sure this would break the Gulp compile. The problem is not that 'lang="sass"' is in the tag, it's that the PHPstorm debug complains that the newer SCSS syntax is wrong when it's not. If you use SCSS syntax and include 'lang="sass"' it will compile but 'lang="scss"' will not.

**Comment by ZhihaoLau** [comment]
This works for me! pls pass the PR

**Comment by ZhihaoLau** [comment]
With 'lang="sass"' and scss code together also can be compiled. But my Atom don't recognize scss syntax with 'lang="sass"' tag. This PR solve my problem.

**Comment by GregPeden** [comment]
Can you compile with lang="scss"? I can't

**Comment by dio-az** [comment]
@SirLamer With this changes you can compile using both languages `scss` and `sass`, but without how are using Atom with [Vue](https://atom.io/packages/language-vue) will see an syntax error.

**Comment by shealan** [comment]
This fixes the error for me 👍

**Comment by dio-az** [comment]
@yyx990803 can you resolve this PR?

**Comment by ZhihaoLau** [comment]
@diogoazevedos 

Nope.. Just find out a better solution. In Laravel's docs, there's one line saying:

> If you'd like to leverage more of Webpack's functionality, Elixir will read any webpack.config.js file that is in your project root and factor its configuration into the build process.

That means you can create `webpack.config.js` file in your project root, and re-run `npm run dev`.

```
module.exports = {
  vue: {
    loaders: {
      js: 'buble-loader',
      scss: 'vue-style!css!sass'
    }
  }
}
```

Because `laravel-elixir-vue-2` will merge your webpack config using `Elixir.webpack.mergeConfig`.
Problem solve, pls close this PR. @yyx990803

**Comment by dio-az** [comment]
@ziolau This works like a charm.

**Pull request closed without merging**
